version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: src/Backend/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - env/conecton.env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./src/Backend:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - env/conecton.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
